/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gmgmultiverso;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gema
 */
public class infoProducto extends javax.swing.JDialog {


    private String nombreProducto;
    private int cantidadProductosEnCarrito;
    
    
    /**
     * Creates new form infoProducto
     */
public infoProducto(java.awt.Frame parent, boolean modal, int contadorCarrito) {
    super(parent, modal);
    initComponents();
}

 public void setNombreProducto(String nombreProducto, double precioProducto) {
    this.nombreProducto = nombreProducto;
    // Mostrar el nombre del producto en el label correspondiente
    name.setText(nombreProducto);
    // Mostrar el precio del producto en el label correspondiente
    precio.setText(String.valueOf(precioProducto));
    // Cargar la imagen 
    ImageIcon imageIcon = null;
    switch (nombreProducto) {
        case "Hamburguesa":
            imageIcon = new ImageIcon(getClass().getResource("/img/burger.png"));
            break;
        case "Hamburguesa Vegana":
            imageIcon = new ImageIcon(getClass().getResource("/img/burgervegan.png"));
            break;
        case "Pizza":
            imageIcon = new ImageIcon(getClass().getResource("/img/pizza.png"));
            break;
        case "Pasta":
            imageIcon = new ImageIcon(getClass().getResource("/img/pasta.png"));
            break;
        case "Arroz":
            imageIcon = new ImageIcon(getClass().getResource("/img/arroz.png"));
            break;
        case "Tostadas":
            imageIcon = new ImageIcon(getClass().getResource("/img/tostadas.png"));
            break;
        default:
            // En caso de que el nombre del producto no coincida con ninguno esperado, mostrar un mensaje de error
            name.setText("Error: Producto no encontrado");
            break;
    }
    if (imageIcon != null) {
        Image image = imageIcon.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(image));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 221, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setText("Nombre del producto ");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 216, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 263, 274));

        jButton1.setText("Añadir al carrito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, 29));

        jLabel2.setText("Precio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 130, -1));

        precio.setText("jLabel3");
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel4.setText("Nombre del Producto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Cerrar la ventana de infoProducto
    dispose();    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Crear una instancia de la pantalla cliente
            PantallaCliente pantallaCliente = new PantallaCliente();
            // Hacer visible la pantalla cliente
            pantallaCliente.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
