/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gmgmultiverso;

import java.awt.Color;

/**
 *
 * @author geanina.foanta
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(860, 500);
        //[860, 500]
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        labelIniciarSesion = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        ingresarUsuario = new javax.swing.JTextField();
        labelContrasenia = new javax.swing.JLabel();
        ingresarContrasenia = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JButton();
        userIcono = new javax.swing.JLabel();
        llave = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar sesión Administrador");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIniciarSesion.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        labelIniciarSesion.setText("Iniciar sesión");
        jPanel1.add(labelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 180, 50));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelUsuario.setText("Administrador");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        ingresarUsuario.setForeground(new java.awt.Color(204, 204, 204));
        ingresarUsuario.setText("Ingrese su nombre de usuario");
        ingresarUsuario.setBorder(null);
        ingresarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarUsuarioMousePressed(evt);
            }
        });
        jPanel1.add(ingresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 240, 30));

        labelContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelContrasenia.setText("Contraseña");
        jPanel1.add(labelContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        ingresarContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarContraseniaMousePressed(evt);
            }
        });
        jPanel1.add(ingresarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 240, 30));

        botonIniciarSesion.setBackground(new java.awt.Color(153, 51, 255));
        botonIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarSesion.setText("Iniciar sesión");
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 30));

        userIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        userIcono.setText("jLabel1");
        jPanel1.add(userIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 30, 30));

        llave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llave.png"))); // NOI18N
        llave.setText("jLabel2");
        jPanel1.add(llave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 30, 30));

        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoLogin.png"))); // NOI18N
        jPanel1.add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarUsuarioMousePressed
        // TODO add your handling code here:
        if (ingresarUsuario.getText().equals("Ingrese su nombre de usuario")) {
            ingresarUsuario.setText("");
            ingresarUsuario.setForeground(Color.black);
        }
        if (String.valueOf(ingresarContrasenia.getPassword()).isEmpty()) {
            ingresarContrasenia.setText("********");
            ingresarContrasenia.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingresarUsuarioMousePressed

    private void ingresarContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarContraseniaMousePressed
        // TODO add your handling code here:
        if (String.valueOf(ingresarContrasenia.getPassword()).equals("********")) {
            ingresarContrasenia.setText("");
            ingresarContrasenia.setForeground(Color.black);
        }
        if (ingresarUsuario.getText().isEmpty()) {
            ingresarUsuario.setText("Ingrese su nombre de usuario");
            ingresarUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ingresarContraseniaMousePressed

    private void botonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseClicked
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + ingresarUsuario.getText() + "\nContraseña: " + String.valueOf(ingresarContrasenia.getPassword()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JPasswordField ingresarContrasenia;
    private javax.swing.JTextField ingresarUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContrasenia;
    private javax.swing.JLabel labelIniciarSesion;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel llave;
    private javax.swing.JLabel userIcono;
    // End of variables declaration//GEN-END:variables
}
